server:
  port: 9296
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geanca-coder/spring-boot-microservices-project
          clone-on-start: true
