spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springdemo
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: DEPARTMENT-SERVICE

server:
  port: 9001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
