apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
      - name: cloud-config-server-app
        image: geancarlocoder/cloud-config-server:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9296
---

apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server-svc
spec:
  selector:
    app: cloud-config-server-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9296
